import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomTabs from "@/components/ui/BottomTabs";
import TopBar from "@/components/ui/TopBar";
import TermsGate from "@/components/ui/TermsGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh bg-background text-foreground pt-12`}
      >
        <TermsGate>
          <TopBar />
          <div className="md:max-w-md md:mx-auto pt-2 pb-16">{children}</div>
          <BottomTabs />
        </TermsGate>
      </body>
    </html>
  );
}
